package app

import "strings"

func rootHelpText() string {
	return strings.Join([]string{
		"prtr is the AI Work Session Manager.",
		"",
		"Start a focused work session, let Claude drive, checkpoint progress, and hand off cleanly.",
		"",
		"Session commands:",
		"  prtr review [files...]     코드 리뷰 세션 시작",
		"  prtr edit [files...]       코드 수정 세션 시작",
		"  prtr fix [files...]        버그 수정 세션 시작",
		"  prtr design [files...]     설계 세션 시작",
		"  prtr checkpoint <note>     진행 상황 메모 (핸드오프 품질 향상)",
		"  prtr done                  세션 완료 처리",
		"  prtr sessions              과거 세션 목록",
		"",
		"Other commands:",
		"  prtr inspect [message...]",
		"  prtr history [search <query>]",
		"  prtr doctor [--fix]",
		"  prtr version",
		"",
		"Advanced commands:",
		"  prtr templates <list|show>",
		"  prtr profiles <list|show|use>",
		"  prtr rerun <id> [flags]",
		"  prtr pin <id>",
		"  prtr favorite <id>",
		"  prtr setup",
		"  prtr lang",
		"  prtr init",
	}, "\n")
}

func setupHelpText() string {
	return strings.Join([]string{
		"Run the advanced guided setup flow.",
		"",
		"`prtr setup` is the compatibility path for people who want the full",
		"interactive defaults flow instead of the smaller first-run path in `start`.",
		"",
		"What `setup` asks for:",
		"  - DeepL API key",
		"  - default input language",
		"  - default output language",
		"  - default app",
		"  - default role",
		"  - default template preset",
	}, "\n")
}

func doctorHelpText() string {
	return strings.Join([]string{
		"Run environment and configuration diagnostics.",
		"",
		"`prtr doctor` checks config, translation readiness, clipboard support,",
		"launchers, automation, and the current platform matrix.",
		"",
		"Usage:",
		"  prtr doctor",
		"  prtr doctor --fix",
		"",
		"`--fix` applies safe automatic fixes when possible, then prints fallback",
		"suggestions for anything it cannot repair automatically.",
	}, "\n")
}

func startHelpText() string {
	return strings.Join([]string{
		"Run the beginner-first first-send flow.",
		"",
		"`prtr start` helps you get from setup to a real first send with as little",
		"friction as possible.",
		"",
		"What `start` does:",
		"  1. Prompts for minimal onboarding settings when needed",
		"  2. Runs `prtr doctor` before the first send",
		"  3. Asks for a first request if you do not pass one",
		"  4. Sends the request through the same flow as `prtr go`",
		"",
		"Usage:",
		"  prtr start [message...]",
		"",
		"Examples:",
		"  prtr start",
		`  prtr start "이 함수 왜 느린지 설명해줘"`,
		`  prtr start --to codex "왜 테스트가 깨지는지 찾아줘"`,
		"  prtr start --dry-run",
		"",
		"Flags:",
		"      --to <app>        Choose the app: claude | codex | gemini",
		"      --dry-run         Show the first-send prompt without opening any app",
		"  -h, --help            Help for start",
		"",
		"Advanced setup:",
		"  Use `prtr setup` when you want the full configuration flow for role,",
		"  template preset, and other advanced defaults.",
	}, "\n")
}

func goHelpText() string {
	return strings.Join([]string{
		"Turn logs, diffs, and intent into the next AI action.",
		"",
		"`prtr go` is the fastest way to use prtr for real work.",
		"",
		"Write in your language when you need translation.",
		"Pipe logs or stack traces when you have evidence.",
		"prtr shapes the request for Claude, Codex, or Gemini and keeps the next step cheaper.",
		"",
		"Works without a DeepL key — AI targets handle multilingual input natively.",
		"Use `prtr demo` if you want a safe preview before setup.",
		"",
		"Usage:",
		"  prtr go [mode] [message...]",
		"",
		"Modes:",
		"  ask       General questions and everyday prompting (default)",
		"  review    Review code, docs, PRs, or plans",
		"  fix       Diagnose errors, logs, and broken tests",
		"  design    Plan implementations, architecture, or UX flows",
		"",
		"How input works:",
		"  - If you pass a message, that message is your request.",
		"  - If you pipe text and also pass a message, the piped text becomes evidence.",
		"  - If you only pipe text, the piped text becomes the request.",
		"  - If you are inside a Git repo, prtr may attach lightweight repo context",
		"    unless --no-context is used.",
		"",
		"What `go` does:",
		"  1. Reads your request",
		"  2. Collects useful context from stdin and the current repo",
		"  3. Translates only when needed",
		"  4. Applies the selected mode",
		"  5. Opens Claude, Codex, or Gemini",
		"  6. Pastes the final prompt",
		"  7. Saves the run so you can swap or run again",
		"",
		"Examples:",
		`  prtr go "이 에러 원인 분석해줘"`,
		`  prtr go review "이 PR에서 위험한 부분만 짚어줘"`,
		`  npm test 2>&1 | prtr go fix "왜 깨지는지 정확한 원인만 찾아줘"`,
		`  prtr go design "이 기능 구조 설계해줘" --to gemini --edit`,
		`  prtr go "이 문서 설명해줘" --dry-run`,
		`  cat crash.log | prtr go fix`,
		"",
		"Flags:",
		"      --to <app>        Choose the app: claude | codex | gemini",
		"      --edit            Review and edit before sending",
		"      --dry-run         Show the final prompt without opening any app",
		"      --no-context      Do not attach repo or piped context automatically",
		"      --no-copy         Do not copy the final prompt to the clipboard",
		"  -h, --help            Help for go",
		"",
		"Next steps:",
		"  prtr swap <app>       Send the last prompt to another app",
		"  prtr take <action>    Turn clipboard text into the next action",
		"  prtr learn            Teach prtr your repo terms and style",
		"  prtr again            Run the latest flow again",
		"  prtr inspect          Inspect the compiled prompt and config",
	}, "\n")
}

func demoHelpText() string {
	return strings.Join([]string{
		"Preview prtr's core loop.",
		"",
		"`prtr demo` is a safe preview path.",
		"It shows the command-layer story with a Korean fix request, sample npm test evidence,",
		"and a Codex-ready prompt preview without launching an app or touching the clipboard.",
		"",
		"Usage:",
		"  prtr demo",
		"",
		"Notes:",
		"  - No API key required",
		"  - No launch, paste, or clipboard writes",
		"  - Uses sample evidence and preview output only",
		"",
		"Try next:",
		`  prtr go "explain this error" --dry-run`,
		"  prtr setup",
	}, "\n")
}

func againHelpText() string {
	return strings.Join([]string{
		"Run the latest prompt flow again.",
		"",
		"`prtr again` reuses the latest request, mode, app, and translation settings.",
		"",
		"Usage:",
		"  prtr again [message...]",
		"",
		"If you pass a new message, it replaces the last request.",
		"If you pipe text and also pass a message, the piped text becomes evidence.",
		"",
		"Examples:",
		"  prtr again",
		"  prtr again --edit",
		`  prtr again "이전 질문을 더 날카롭게 다시 물어봐줘"`,
		"",
		"Flags:",
		"      --edit            Review and edit before sending",
		"      --dry-run         Show the final prompt without opening any app",
		"      --no-context      Do not attach repo or piped context automatically",
		"      --no-copy         Do not copy the final prompt to the clipboard",
		"  -h, --help            Help for again",
	}, "\n")
}

func swapHelpText() string {
	return strings.Join([]string{
		"Send the latest prompt to another app.",
		"",
		"`prtr swap` reuses the latest request and mode, then recompiles it for",
		"Claude, Codex, or Gemini without rebuilding the flow manually.",
		"",
		"Usage:",
		"  prtr swap <app> [message...]",
		"",
		"Examples:",
		"  prtr swap claude",
		"  prtr swap codex",
		"  prtr swap gemini",
		"  prtr swap gemini --edit",
		"  prtr swap claude --dry-run",
		"",
		"Flags:",
		"      --edit            Review and edit before sending",
		"      --dry-run         Show the final prompt without opening any app",
		"      --no-context      Do not attach repo or piped context automatically",
		"      --no-copy         Do not copy the final prompt to the clipboard",
		"  -h, --help            Help for swap",
	}, "\n")
}

func takeHelpText() string {
	return strings.Join([]string{
		"Turn the latest answer or clipboard text into the next action.",
		"",
		"`prtr take` has two paths:",
		"  - classic: turn clipboard text into the next ready-to-send prompt",
		"  - deep: build a typed execution run with artifacts, plan, and progress",
		"",
		"Usage:",
		"  prtr take <action> [--dip] [flags]",
		"",
		"Classic actions (all support --deep for patch/test/debug/refactor):",
		"  patch     Turn the answer into an implementation prompt",
		"  test      Turn the answer into a testing prompt",
		"  debug     Turn the answer into a debugging prompt",
		"  refactor  Turn the answer into a refactoring prompt",
		"  commit    Turn the answer into a commit message prompt",
		"  summary   Turn the answer into a short reusable summary prompt",
		"  clarify   Turn the answer into a clarification prompt",
		"  issue     Turn the answer into an issue or task prompt",
		"  plan      Turn the answer into an implementation plan prompt",
		"",
		"Classic examples:",
		"  prtr take patch",
		"  prtr take patch --dip --dry-run",
		"  prtr take test --to codex",
		"  prtr take commit --dry-run",
		"  prtr take summary --edit",
		"  prtr take issue",
		"  prtr take plan",
		"",
		"Deep execution engine examples:",
		"  prtr take patch --dip",
		"  prtr take patch --dip --dry-run    # write artifacts; skip opening app",
		"  prtr take patch --dip --to claude  # route delivery to Claude",
		"  prtr take patch --dip --llm        # enable LLM enhancement (uses config)",
		"  prtr take patch --dip --llm=claude # specify LLM provider",
		"",
		"Flags:",
		"      --to <app>        Choose the app: claude | codex | gemini",
		"      --dip            Run the internal execution engine for `take patch`",
		"      --deep           Alias for --dip (deprecated)",
		"      --llm            Enable LLM enhancement (provider from config or PRTR_LLM_PROVIDER)",
		"      --llm=<provider> Enable LLM enhancement with explicit provider",
		"      --edit            Review and edit before sending",
		"      --dry-run         Show the final prompt without opening any app",
		"                        Deep mode still writes plan and artifact files locally",
		"  -h, --help            Help for take",
	}, "\n")
}

func learnHelpText() string {
	return strings.Join([]string{
		"Teach prtr your repo terms and style.",
		"",
		"`prtr learn` scans your project and builds a local termbook with",
		"protected project terms that should not be translated away.",
		"",
		"Usage:",
		"  prtr learn [paths...]",
		"",
		"If no paths are provided, prtr learns from README, docs, cmd, and internal.",
		"",
		"Examples:",
		"  prtr learn",
		"  prtr learn README.md docs",
		"  prtr learn --dry-run",
		"  prtr learn --reset",
		"",
		"Flags:",
		"      --dry-run         Show the generated termbook without saving",
		"      --reset           Rebuild the termbook instead of merging it",
		"  -h, --help            Help for learn",
	}, "\n")
}

func inspectHelpText() string {
	return strings.Join([]string{
		"Inspect the compiled prompt and resolved config without sending it anywhere.",
		"",
		"`prtr inspect` is the expert path for diff, explain, JSON output, and",
		"advanced prompt-shaping flags.",
		"",
		"Usage:",
		"  prtr inspect [flags] [message...]",
		"",
		"Examples:",
		`  prtr inspect "이 PR 리뷰해줘"`,
		`  prtr inspect --json "이 에러 분석해줘"`,
		`  prtr inspect -t codex --template codex-implement -r be "이 함수 개선해줘"`,
		"",
		"Flags:",
		"  -t, --target <name>    target profile name",
		"      --source-lang <code> advanced source language override",
		"      --to <code>        target language override",
		"  -r, --role <alias>     role profile alias",
		"      --template <name>  template preset name",
		"      --translation-mode auto|force|skip",
		"  -i, --interactive      edit the final prompt in a TUI before output",
		"      --show-original    print the original input to stderr",
		"      --explain          print resolved configuration details to stderr",
		"      --diff             print original, translated, and final prompt to stderr",
		"      --json             emit structured JSON output",
		"      --no-copy          print the translated prompt without copying it",
		"  -h, --help             Help for inspect",
	}, "\n")
}
